### ISSUE TITLE
Server favicon bug

### ISSUE THREAD

**Issue by tjeufoolen** [Cryptkeeper/Minetrack#104]
Some servers have no favicon and return `server-icon.png` as `src` instead of the `MISSING_FAVICON_BASE64`

**Comment by Cryptkeeper** [comment]
Indirectly fixed by https://github.com/Cryptkeeper/Minetrack/commit/0392fce6c3c313e649d9f9d7b63e45b7f89b42fa#diff-2ecbd0af8445bfe9703be0daab2916eaR18
