### ISSUE TITLE
Errors, on node app.js

### ISSUE THREAD

**Issue by SantaKeeper** [Cryptkeeper/Minetrack#11]
if i try to run the Minetrack with ```node app.js``` it is giving this error?
Any solution on how to fix this?

```app.js:98 graphData[network.ip].push([timeMs, res ? res.players.online : 0]);```

```TypeError: Cannot read property 'push' of undefined
app.js:98:27
ping.js:37:4
node_modules\mcpe-ping\index.js:157:9
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:480:8)```

**Comment by Cryptkeeper** [comment]
Fixed in 7ea8332a524fe5d53e7f34a42aa8bd67092294f4, pull and it should be fixed.
