### ISSUE TITLE
Error running app.js

### ISSUE THREAD

**Issue by danjb2000** [Cryptkeeper/Minetrack#12]
[Solved]

New issue: 

20:32:29 26/12/15 - info: Booting, please wait...
20:32:29 26/12/15 - warn: Database logging is not enabled. You can enable it by setting "logToDatabase" to true in config.json. This requires sqlite3 to be installed.
20:32:29 26/12/15 - info:  0=/, 1=/images/compass.png, 2=/js/site.js, 3=/js/util.js, 4=/css/main.css, 5=/favicons/hypixelpe.png, 6=/favicons/lifeboat.png, 7=/favicons/mineplex.png, 8=/favicons/mobcrush.png
20:32:29 26/12/15 - info: Started on 0.0.0.0:8080
20:32:29 26/12/15 - error: Failed to ping play.hivemc.com: {}
20:32:29 26/12/15 - error: Failed to ping play.cubecraftgames.net: {}
20:32:29 26/12/15 - error: Failed to ping us.oc.tc: {}
20:32:29 26/12/15 - error: Failed to ping mc.hypixel.net: {}
20:32:30 26/12/15 - error: Failed to ping play.hivemc.com: {}
20:32:30 26/12/15 - error: Failed to ping play.cubecraftgames.net: {}
20:32:31 26/12/15 - error: Failed to ping us.oc.tc: {}
20:32:31 26/12/15 - error: Failed to ping mc.hypixel.net: {}
20:32:46 26/12/15 - error: Failed to ping play.cubecraftgames.net: {}
20:33:00 26/12/15 - error: Failed to ping mc.hypixel.net: {}
20:33:29 26/12/15 - error: Failed to ping play.hivemc.com: {}
20:33:29 26/12/15 - error: Failed to ping play.cubecraftgames.net: {}
20:33:29 26/12/15 - error: Failed to ping us.oc.tc: {}
20:33:30 26/12/15 - error: Failed to ping mc.hypixel.net: {}
20:33:30 26/12/15 - error: Failed to ping play.hivemc.com: {}
20:33:30 26/12/15 - error: Failed to ping play.cubecraftgames.net: {}
20:33:31 26/12/15 - error: Failed to ping us.oc.tc: {}
20:33:32 26/12/15 - error: Failed to ping mc.hypixel.net: {}

**Comment by danjb2000** [comment]
New issue: 


20:32:29 26/12/15 - info: Booting, please wait...
20:32:29 26/12/15 - warn: Database logging is not enabled. You can enable it by setting "logToDatabase" to true in config.json. This requires sqlite3 to be installed.
20:32:29 26/12/15 - info:  0=/, 1=/images/compass.png, 2=/js/site.js, 3=/js/util.js, 4=/css/main.css, 5=/favicons/hypixelpe.png, 6=/favicons/lifeboat.png, 7=/favicons/mineplex.png, 8=/favicons/mobcrush.png
20:32:29 26/12/15 - info: Started on 0.0.0.0:8080
20:32:29 26/12/15 - error: Failed to ping play.hivemc.com: {}
20:32:29 26/12/15 - error: Failed to ping play.cubecraftgames.net: {}
20:32:29 26/12/15 - error: Failed to ping us.oc.tc: {}
20:32:29 26/12/15 - error: Failed to ping mc.hypixel.net: {}
20:32:30 26/12/15 - error: Failed to ping play.hivemc.com: {}
20:32:30 26/12/15 - error: Failed to ping play.cubecraftgames.net: {}
20:32:31 26/12/15 - error: Failed to ping us.oc.tc: {}
20:32:31 26/12/15 - error: Failed to ping mc.hypixel.net: {}
20:32:46 26/12/15 - error: Failed to ping play.cubecraftgames.net: {}
20:33:00 26/12/15 - error: Failed to ping mc.hypixel.net: {}
20:33:29 26/12/15 - error: Failed to ping play.hivemc.com: {}
20:33:29 26/12/15 - error: Failed to ping play.cubecraftgames.net: {}
20:33:29 26/12/15 - error: Failed to ping us.oc.tc: {}
20:33:30 26/12/15 - error: Failed to ping mc.hypixel.net: {}
20:33:30 26/12/15 - error: Failed to ping play.hivemc.com: {}
20:33:30 26/12/15 - error: Failed to ping play.cubecraftgames.net: {}
20:33:31 26/12/15 - error: Failed to ping us.oc.tc: {}
20:33:32 26/12/15 - error: Failed to ping mc.hypixel.net: {}

**Comment by Cryptkeeper** [comment]
I made some tweaks in https://github.com/Cryptkeeper/Minetrack/commit/b31d66d1b3c5454253d731a4cb5609bc8b1aeb35 that should help with this (slower ping rate, properly printing the error message.) 

Can you pull down the changes and give it a spin and comment back with any new errors?

Thanks!

**Comment by danjb2000** [comment]
Got it now anyway - thanks. All's working now.

Just one final after-thought, would it ever be possible to have this application run straight off my regular web-server in a directory as apposed to having to have it run on its own port e.t.c? Means I'm constantly showing people it with :8080 when I have a perfectly good web-server on :80 :P

**Comment by Cryptkeeper** [comment]
Not really since they would be to separate processes. But if you're up for an adventure, you could use something like haproxy to redirect the different requests to the different servers while maintaining one address that responds on one port.

http://www.haproxy.org/
