### ISSUE TITLE
How are you supposed to make subdomains instead of ports

### ISSUE THREAD

**Issue by MooMooYT** [Cryptkeeper/Minetrack#123]
For example I want track1.domain.com to be port 8080
and I want track2.domain.com to be port 8081
How are you supposed to do this?

**Comment by MiniDigger** [comment]
This is really not the place to ask such questions...
Anyways, two possible solutions: a reverse proxy (haproxy, traefik, if it's just http even nginx) or srv records (those can be iffy)
