### ISSUE TITLE
sqlite database getting too big

### ISSUE THREAD

**Issue by MooMooYT** [Cryptkeeper/Minetrack#126]
Hello, so my sqlite database is getting too big, (more than 2GB+) and I was wondering how I can reduce the amount of disk space it uses.

![image](https://user-images.githubusercontent.com/48740106/60151040-3d95b780-97a9-11e9-8ac5-22670ac8cc8f.png)

**Comment by SubscriberRocks** [comment]
1. Reset it
2. Query less servers

**Comment by MooMooYT** [comment]
> 1. Reset it
> 2. Query less servers

If I reset it, will the player record reset also?

**Comment by SubscriberRocks** [comment]
I think so. There is no way to decrease the space it uses unless you reset it every day,

**Comment by hugmanrique** [comment]
Alternatively, you can install a SQLite client and run the following query (I haven't tested it and I would save a backup before running it):

```sql
DELETE FROM pings WHERE playerCount NOT IN (
  SELECT maxCount FROM (
    SELECT MAX(playerCount) AS maxCount FROM pings GROUP BY ip
  )
);
```

This query is not perfect: it will leave duplicates and pings from other IPs that don't correspond to the server's IP (e.g. Server A has a record of 20 players, Server B has a record of 25 players, Server B has multiple pings with 20 players -> this script will leave all those pings). However, this query will probabily reduce your file site by multiple orders of magnitude.

**Comment by Cryptkeeper** [comment]
I manually query the max playerCount per IP myself and re-insert them into a new SQLite database. If you end up removing records from your existing database, make sure to VACUUM: https://www.sqlite.org/lang_vacuum.html

As for Minetrack, this isn't something supported and won't be. I'm prototyping rebuilding Minetrack into a more generic solution written in Go, and if everything works out, I can slate it as a feature there.
