### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by belohnung** [Cryptkeeper/Minetrack#127]
/root/Minetrack/node_modules/mcpe-ping-fixed/index.js:149
          'cleanName': pong.name.replace(/\xA7[0-9A-FK-OR]/ig, ''),
                                 ^

TypeError: Cannot read property 'replace' of undefined
    at /root/Minetrack/node_modules/mcpe-ping-fixed/index.js:149:34
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)

**Comment by hugmanrique** [comment]
Some MCPE server in your config.json file is returning invalid ping data (missing the `name` field)

**Comment by belohnung** [comment]
Could we try to not crash when that happens?

**Comment by JohnyMuffin** [comment]
We should add some print outs that explain the errors but it was a improper config. I believe that Minetrack is focused towards people who already have a little experience with coding.

**Comment by belohnung** [comment]
I have experience in coding but not in node
