### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by SuprexDE** [Cryptkeeper/Minetrack#129]
Hello, I have a problem!
For me, the large overview window will not be displayed. What should I do?

And i have one Question: 
How can I add the server picture?

Screenshots: http://prntscr.com/p9iytd
I want to this on my Website: http://prntscr.com/p9iyxk

**Comment by hugmanrique** [comment]
I believe you need to enable database logging in the `config.json` file. Take a look at the `README` file for more detailed instructions.

**Comment by RubyTemple** [comment]
@hugmanrique how i can add this https://prnt.sc/q4kzy2 in my site? https://prnt.sc/q4kzpj

Thanks
