### ISSUE TITLE
Stuck on Connecting

### ISSUE THREAD

**Issue by gameshowrecaps** [Cryptkeeper/Minetrack#130]
minetrack.me will not load or any of the sites, bedrock.minetrack.me, and the roblox site. They are all stuck on connecting. Is it just me?

**Comment by gameshowrecaps** [comment]
It seems to work on Firefox. What's going on? It won't work on my phone.

**Comment by MiniDigger** [comment]
What's browser does your phone uses? Which version? Which os? Which os version?

**Comment by gameshowrecaps** [comment]
Never mind it works now. Turns out blocking adblock and popup blocking caused it to screw up loading. It is all fixed now.
