### ISSUE TITLE
Connecting Stuck..

### ISSUE THREAD

**Issue by SizickOfficial** [Cryptkeeper/Minetrack#133]
Hello, i've installed it and when i'm trying to connecting on my web browser i'm stuck on "Connecting.."
I use Brave and i've tryied to disable all of my adblock. I've try with Microsoft Edge with the same result.

The console spam the log:
info: x.x.x.x connected, total client: x

The tracker is on a vps on ubuntu 18 with NodeJS v8.10.0 and npm v3.5.2.
I have tryied with nodejs 12.x and npm with it not working too

Someone has an idea ? :/

**Comment by hugmanrique** [comment]
Mind opening your browser console and seeing if there's any websocket errors?

**Comment by SizickOfficial** [comment]
The only thing i have on the console is 
![wpYqcXmQmf](https://user-images.githubusercontent.com/35431335/75276929-63c39980-5807-11ea-92d6-15e742087ce7.png)

And theses DevTools error are here all time on all website i access but i don't think its the problem :/

**Comment by Cryptkeeper** [comment]
Try connecting to {your-website-here.com}/publicConfig.json (for example, https://minetrack.me/publicConfig.json). It should return a page with some JSON text, ignore that. This is just a test to see if your firewall is open and the server is bound to the correct port.

**Comment by SizickOfficial** [comment]
Hello @Cryptkeeper ,
![2lHnPFY9id](https://user-images.githubusercontent.com/35431335/76767875-90315c80-679a-11ea-9329-6a5c618edf6a.png)

That return the JSON text 🤔

**Comment by hugmanrique** [comment]
Are you running the latest version? Getting stuck on "Connecting..." and getting the connected message on the backend indicates there's some problem between the initial connection and the validation.

For some reason this first `bootTime` message sent from the backend isn't reaching the client:
https://github.com/Cryptkeeper/Minetrack/blob/557c581726a0ef8db963c9d707a3ed3572c574ac/app.js#L206

**Comment by SizickOfficial** [comment]
Hello, i has my discord bots started on the same VPS (in Java [JDA]).

I tested to stop all of my bots to start one of 2 trackers instance, one work fine now, but the second does the same 🤔

**Comment by hugmanrique** [comment]
I assume the `site.port` value is different on both trackers, if not you would get an `EADDRINUSE` error...

The backend definitely uses that IP and port to create the server (https://github.com/Cryptkeeper/Minetrack/blob/master/lib/server.js#L101, https://github.com/Cryptkeeper/Minetrack/blob/master/lib/server.js#L104). However the socket.io client must do some magic to guess the IP and port from the browser's URL (https://github.com/Cryptkeeper/Minetrack/blob/master/assets/js/site.js#L266). I believe this magic is currently breaking multitracker setups. Run both trackers at the same time, go to the Network tab on your browser and send a screenshot of both trackers' requests.

**Comment by Cryptkeeper** [comment]
Ah, yeah if you're running multiple you should probably considering using something like subdomains+nginx vhosts (it's how I run minetrack.me's different instances). It's a bit messy, but it will create cleanly defined routing lines and stop this kind of silent clashing behavior.
