### ISSUE TITLE
Unusual player count crashes browser

### ISSUE THREAD

**Issue by videosambo** [Cryptkeeper/Minetrack#134]
I did have one server on my tracker that used some kind of plugin to make its player count impossible high. This player count did crash my browser and I found out that the bigger graph is the problem.
[https://cdn.discordapp.com/attachments/239743391871533056/684481765318197383/unknown.png](https://cdn.discordapp.com/attachments/239743391871533056/684481765318197383/unknown.png)

**Comment by Cryptkeeper** [comment]
Fixed in https://github.com/Cryptkeeper/Minetrack/commit/6d0a2f28e5145efe506ae7413477260d404bd3e7

It imposes a limit of 250,000. You may find that's too high for your use case and wish to lower it.
