### ISSUE TITLE
24 hour peak "undefined"

### ISSUE THREAD

**Issue by JollyajaX** [Cryptkeeper/Minetrack#138]
24-hour peak will include "undefined" text when the user's local clock is set to 24 hour time.

![Undefined](https://screenie.club/i/p9jjuasrk3.png)

This is because the javascript relies on the result of `toLocaleTimeString()` to be in 12 hour format:

```
function updateServerPeak(name, time, playerCount) {
	var safeNameCopy = safeName(name);
	// hack: strip the AM/PM suffix, this could just use a date format instead
	var timestamp = getTimestamp(time / 1000).split(':');
	var end = timestamp.pop().split(' ')[1];
	timestamp = timestamp.join(':') + ' ' + end;
	$('#peak_' + safeNameCopy).html('24h Peak: ' + formatNumber(playerCount) + ' @ ' + timestamp);
}
```

meaning end is null/undefined. Simple fix would be check if end is not undefined, but figured you might want to code a more robust way to render the time.

**Comment by Cryptkeeper** [comment]
Hacked the hack and fixed in https://github.com/Cryptkeeper/Minetrack/commit/65aabb179a1fa1f562e11529138e7f6c2b9fde2b.

Thanks!
