### ISSUE TITLE
a "port": "(port)" in the config.json

### ISSUE THREAD

**Issue by SantaKeeper** [Cryptkeeper/Minetrack#14]
Hello,
Are you able to make a "port": "(port)", in the config.json?

as example
```
	"servers": [
		{
			"name": "Test",
			"ip": "127.0.0.1",
			"port": "25566",
			"type": "PC"
		}
```

**Comment by Cryptkeeper** [comment]
Yes. 

If you don't provide a port, it will automatically assume on given the type (19132 for PE, 25565 for PC).

**Comment by TNTUP** [comment]
Hi, I tried adding "port": "25585", and it doesn't work in servers.json :/
