### ISSUE TITLE
Everything fails to ping

### ISSUE THREAD

**Issue by KermanIsPretty** [Cryptkeeper/Minetrack#141]
Hi, when using my own installation on an OVH VPS pinging is slow and times out if the value is not over 15000ms for timeout, when adding some servers seem to throw this [error ](https://hasteb.in/meteqoni.js)

**Comment by GiansCode** [comment]
To addon to the above ^ this is to do with the ping lib that's being used. Chances are you're trying to track a server which is blocked by Mojang and using DNS rotation to bypass it. I had the same issue with a server that would end up pinging "1werg39rgi3gh2eiog39rgijgsiuhi2urgirj22e.ddns.net"

**Comment by hugmanrique** [comment]
I found the issue, but [mc-ping-updated](https://github.com/Cryptkeeper/mc-ping-updated/) has been archived so I can't PR it. `CustomBuffer` initially allocates a buffer with length `48`, and all write operations internally call `writeUByte`, which is in charge of resizing the buffer if necessary.

This is the [resizing code](https://github.com/Cryptkeeper/mc-ping-updated/blob/master/lib/mcpc_buffer.js#L41):

```js
if (offset + 1 >= buffer.length) {
    Buffer.concat([buffer, new Buffer(50)]);
}
```

There's two problems with this code:

1. If the current write `offset` is exactly equal to the buffer's length, the buffer doesn't get resized and a illegal write at offset `buffer.length` is done.
2. `Buffer.concat` doesn't mutate the original buffer and instead returns a new one, meaning `buffer` still can only hold 48 bytes.

You're hitting issue 2: `The value of "offset" is out of range. It must be >= 0 and <= 47. Received 49`. The buffer length is 48 and `writeUByte` is attempting to write to offset 49. `Buffer.concat` is called, but the original buffer is never reassigned.

A fixed version is:

```js
if (offset >= buffer.length) {
    buffer = Buffer.concat([buffer, new Buffer(50)]);
}
```

**Comment by Cryptkeeper** [comment]
@hugmanrique I've temporarily unarchived mc-ping-updated if you would like to PR that fix. You're free to also fork it completely and push a new version to npm and I'll swap the dependency in Minetrack.

**Comment by Cryptkeeper** [comment]
I've merged the PR into mc-ping-updated under version 0.1.1 and updated Minetrack (commit https://github.com/Cryptkeeper/Minetrack/commit/8c5e25b25905ea580476935151469c604f0956cb) to use the new version. Pull down the changes and run `npm install` to get the fix. 

Thanks again for your help @hugmanrique.
