### ISSUE TITLE
Issues regarding the mc-pinger

### ISSUE THREAD

**Issue by XiaoLins** [Cryptkeeper/Minetrack#144]
Some of the servers on my list cannot be pinged correctly (while they are operating steadily)
This issue has appeared since I updated to the 4.0 remake version.
![QQ截图20200410172812](https://user-images.githubusercontent.com/21016349/78980741-1ef28880-7b51-11ea-8995-8d0a549dd460.png)

**Comment by XiaoLins** [comment]
btw all of the servers that cannot be pinged are running on Netease servers and using Netease authentication (however my server is running on Netease servers too but can be pinged correctly)

**Comment by hugmanrique** [comment]
You're getting timed out on those IPs, can you test your connection? For example, run `ping 42.186.67.17` and `nmap -p 25565 42.186.67.17` (I picked one IP on those logs, try with all of them) and report back.

**Comment by XiaoLins** [comment]
I've tried 42.186.67.17 and 42.186.55.238 and the feedback is in the attached files, and others should respond the same as they are from the same data centers. These IPs responded in less than 10ms and are all running Minecraft services (players can connect normally)
![QQ截图20200411015659](https://user-images.githubusercontent.com/21016349/79012005-e1651e00-7b97-11ea-933a-b24d08f4d860.jpg)

**Comment by hugmanrique** [comment]
Can you check if those servers have a favicon?

`res.favicon` in https://github.com/Cryptkeeper/Minetrack/blob/6d0a2f28e5145efe506ae7413477260d404bd3e7/lib/ping.js#L19 is missing an `undefined` check (https://wiki.vg/Server_List_Ping#Response specifies the `favicon` field is optional).

**Comment by XiaoLins** [comment]
That might be the reason. None of these servers have a favicon. How may I fix this?

**Comment by XiaoLins** [comment]
> Can you check if those servers have a favicon?
> 
> `res.favicon` in
> 
> https://github.com/Cryptkeeper/Minetrack/blob/6d0a2f28e5145efe506ae7413477260d404bd3e7/lib/ping.js#L19
> 
> is missing an `undefined` check (https://wiki.vg/Server_List_Ping#Response specifies the `favicon` field is optional).

That might be the reason. None of these servers have a favicon. How may I fix this?

**Comment by XiaoLins** [comment]
The problem is fixed after using the modified ping.js. Thanks a lot!
