### ISSUE TITLE
Graph disappearing

### ISSUE THREAD

**Issue by Oxro** [Cryptkeeper/Minetrack#147]
Since the new update, hovering over one of the lines on the graph can cause some of the other lines on the graph to disappear.

Google Chrome on Windows 10

![image](https://user-images.githubusercontent.com/64044715/79970661-2be57500-848b-11ea-8a09-d82511bf8781.png)

**Comment by Cryptkeeper** [comment]
It appears to be caused by the backend retaining too much historical data and in return rendering some funky graphs. I've deployed a possible fix, please let me know if you see this crop back up.

**Comment by ismhdez** [comment]
Any solution on this?

**Comment by Oxro** [comment]
@ismhdez It's been fixed in latest version.
