### ISSUE TITLE
INSTALLATION ERROR 

### ISSUE THREAD

**Issue by alexeses** [Cryptkeeper/Minetrack#150]
Hello!

I've been following the Minetrack project for a while now, and it's kind of amazing. However, I noticed that it's been updated for days now and I'd be happy to use it. 

Unfortunately I found some bugs when installing it, I use node version 8.10.0 and npm version 3.5.2. 

When you run the command _npm install --build-from-source_ it started installing everything correctly, it finished something like this https://prnt.sc/s4lssy. 

I continued with the command _npm run build_, https://prnt.sc/s4ltb9, unfortunately when trying to start the project the following error is encountered https://prnt.sc/s4ltm3.

Could you give me a hand? Thanks! If you need more information, don't hesitate to ask me.

**Comment by hugmanrique** [comment]
As indicated by [Node.green](https://node.green/#ESNEXT-candidate--stage-3--instance-class-fields) class field declarations have been supported since Node 12.4.0. ([proposal](https://github.com/tc39/proposal-class-fields)) Please update your Node version (you should *always* run the latest version) and try again.

**Comment by alexeses** [comment]
Hey, Hugo!

Nice to see you here, you're partly right, apparently I missed reading. However, when I updated the node to the latest version, the theme for the SQLITE3 module was missing.

I have installed node-v83-linux-x64 instead of node-v79-linux-x64. https://imgur.com/a/Gl5Emxy

Which version do you recommend to use for node-v79-linux-x64. I use node 13.13 and npm 6.14.4 

Greetings.

**Comment by hugmanrique** [comment]
Ah, try removing your node_modules (`rm -rf node_modules`) and install dependencies again using `npm i`.

**Comment by Cryptkeeper** [comment]
Please let me know if the Node version upgrade has resolved this. I've merged @hugmanrique's https://github.com/Cryptkeeper/Minetrack/pull/151 PR which specifies this version requirement in the README and copied it to the Minetrack 5 [docs/MIGRATING.md](https://github.com/Cryptkeeper/Minetrack/blob/master/docs/MIGRATING.md) guide.
