### ISSUE TITLE
Main graph not showing right 

### ISSUE THREAD

**Issue by CS223** [Cryptkeeper/Minetrack#155]
I just installed minetrack and everything works except the big graph itself here is a picture  https://i.imgur.com/lXBHSBG.png also no errors in the logs https://i.imgur.com/UYdQ8bO.png
Here is the site link http://51.89.166.61:8080/

**Comment by Cryptkeeper** [comment]
The graph will look funky while it populates its initial data over the first 24 hours. Give it some time and it will be fine :)
