### ISSUE TITLE
Change graph numbers 

### ISSUE THREAD

**Issue by CS223** [Cryptkeeper/Minetrack#158]
Hey, just a question is there any way I change the numbers on the y-axis instead of 5000 to something else? As the server, I'm tracking servers with less than 400 players and the graph just looks really congested when I'm trying look at all of the servers at ones.

**Comment by hugmanrique** [comment]
See https://github.com/Cryptkeeper/Minetrack/issues/152#issuecomment-618898071, we should probs add a config option for it (or better, make it automatically scale) though.

**Comment by Cryptkeeper** [comment]
I'll see if I can get it to auto scale, otherwise I'll expose a setting directly.

**Comment by Cryptkeeper** [comment]
Release 5.2.1 has this enabled. It's using flot.js' auto scaling behavior so it can't be all that finely tuned, but should create a much better OOB experience for most people. Let me know if it works for you :)

**Comment by CS223** [comment]
Thanks, it works from what I can see thanks again for the help and the fast reply.
