### ISSUE TITLE
24 hour peak time

### ISSUE THREAD

**Issue by Oxro** [Cryptkeeper/Minetrack#160]
Is it intentional that the 24 hour peak's time no longer displays?

![image](https://user-images.githubusercontent.com/64044715/80865637-a62fa980-8c82-11ea-8a45-07b0f9fdd46f.png)

**Comment by TehNeon** [comment]
It should provide a tooltip displaying the time if you hover over it.

**Comment by Cryptkeeper** [comment]
It's been moved to displaying when hovering over the text.
