### ISSUE TITLE
Some icons are not showing up

### ISSUE THREAD

**Issue by Matthew18Dev** [Cryptkeeper/Minetrack#161]
Hi,

after a first restart of node, some servers aren't showing the icons anymore, instead, there's the default one, I tried giving a look at the array returned by "res" in mc-ping-updated but the favicon is completely empty on these, while there actually is a server-icon, looks like it can't see the icon at all.

**Comment by Cryptkeeper** [comment]
Are you still able to reproduce this? Could you send me the servers you're pinging?

**Comment by Cryptkeeper** [comment]
I've fixed this in my bulk-pings branch: https://github.com/Cryptkeeper/Minetrack/tree/bulk-pings

It will be merged soon as version 5.4.0
