### ISSUE TITLE
Bold the server closest to your mouse on the large graph

### ISSUE THREAD

**Issue by szferguson** [Cryptkeeper/Minetrack#169]
Hi,

Awesome job with the recent changes so far! Really dig the new charting library.

Small UX idea: On the large graph that lists all the servers, have the server closest to your mouse **bolded** on the dropdown, so you can easily identify which server you're most interested in.

In addition, a zoom reset button would be fantastic as well!

**Comment by Cryptkeeper** [comment]
Thanks for the suggestions!

I'm working on adding the bold highlight at your suggestion, as well as a smaller "minimap" copy of the historical graph to make panning/zooming easier.

**Comment by Cryptkeeper** [comment]
Reopening so I can use this issue to track progress.

**Comment by Cryptkeeper** [comment]
I've finished these features on my `uplot-test` branch. I will open a release preview for these changes soon.

Thanks again for the suggestion.
