### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by Oxro** [Cryptkeeper/Minetrack#174]
It would be neat if the dates under the historical graph were formatted based on the client, such as dd/mm for countries that use it.

**Comment by Cryptkeeper** [comment]
This formatting behavior comes from uPlot, the graphing library used to render the plots.

I'm not currently seeing a way to customize it, and the formatting logic seems hardwired in. Your best bet is to open a feature request on their repo.

https://github.com/leeoniya/uPlot

**Comment by leeoniya** [comment]
it's unlikely there will be a way to automatically format based on browser locale in uPlot, but you can certainly control all aspects of formatting (see below). whether you choose to pass these options through to your users or handle the "auto" aspect for them is up to you.

https://github.com/leeoniya/uPlot/tree/master/docs#axis--grid-opts

https://github.com/leeoniya/uPlot/blob/master/demos/months-ru.html
