### ISSUE TITLE
Sessions shows as offline when its not

### ISSUE THREAD

**Issue by SecretlyJealous** [Cryptkeeper/Minetrack#177]
Hi,

I recently started using minetrack on my own local machine but for some reason the Minecraft Sessions always shows up as "Offline"

![Untitled](https://user-images.githubusercontent.com/10485646/83976870-c6433000-a8f4-11ea-8697-a7e6850bab35.png)

Is it possible to fix this? It happens on the main site too: https://minetrack.me/

**Comment by hugmanrique** [comment]
This has been going on for ~3 months with the Mojang API returning an incorrect status for sessions.

**Comment by Cryptkeeper** [comment]
As @hugmanrique said, this is being fed from Mojang's status page (`https://status.mojang.com/check`), where "sessionserver.mojang.com" has been returning red for several weeks. I don't know if this is simply a bug on their end or if the Minecraft session endpoint has moved to a new URL.

**Comment by Cryptkeeper** [comment]
Looks like they haven't changed endpoints, just a bug on their end. Nothing I can do unfortunately. 🤷‍♀️

**Comment by MiniDigger** [comment]
we have been forwarding "complains" about this to mojangs web team, they know about it and tried stuff, but its still not really fixed. Ill try to remember to address it again today.
