### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by M4RC0Sx** [Cryptkeeper/Minetrack#178]
I installed Minetrack following the guide steps and using latest versions of node and npm. The server starts correctly, but when I access it from the browser it keeps reconnecting with the regresive countdown and I can´t see any servers, charts or something.

**Comment by Cryptkeeper** [comment]
Are you using any sort of web server like apache/nginx?

**Comment by M4RC0Sx** [comment]
Yes, I am running under a reverse nginx proxy.

**Comment by hugmanrique** [comment]
Follow the steps on https://github.com/Cryptkeeper/Minetrack/issues/167#issuecomment-629714656

**Comment by M4RC0Sx** [comment]
That didn´t work. I have tried accessing directly through the port and not using the nginx proxy, but it keeps connecting.

**Comment by M4RC0Sx** [comment]
I have reinstalled it. It just works well the first tiem I enter the page. When I refresh it, it keeps reconnecting and never finishes loading.

**Comment by Cryptkeeper** [comment]
What web browser are you using? Can you open the Developer Tools, head to "Console" and then refresh the page and copy/paste the output here?

**Comment by M4RC0Sx** [comment]
I have tried with Firefox and Edge. I don´t know what I did but it seems to be working now. Thank you!
