### ISSUE TITLE
Starting

### ISSUE THREAD

**Issue by AndriusTAP** [Cryptkeeper/Minetrack#180]
hi i have no idea what im doing so far ive just downloaded the file and im not sure what to do next.

**Comment by hugmanrique** [comment]
Follow the install instructions on the [README](https://github.com/Cryptkeeper/Minetrack#installation) file.

**Comment by AndriusTAP** [comment]
i did i dont understand what to do like where do i run those "npm" commands and stuff

**Comment by Cryptkeeper** [comment]
Unfortunately if you're not overly familiar with command line interfaces and programs like Nodejs, this is likely going to be too complex to get up and running on a server. 

If you're looking for an easier to use tool for monitoring Minecraft servers, I would recommend digging into something like [mcmyadmin](https://www.mcmyadmin.com/).
