### ISSUE TITLE
Adding a new server bugs out the graph

### ISSUE THREAD

**Issue by isokissa3** [Cryptkeeper/Minetrack#184]
When adding a new server it starts to draw the graph from the left corner instead of the right one. This obviously makes the graph look funny and makes it impossible to compare the values with the current online servers.

Pay attention to the blue line.
![image](https://user-images.githubusercontent.com/3258677/84248596-54e0c880-ab12-11ea-8048-b9e3bb46e0bb.png)

The server is running on https://minetrack.fi

**Comment by Cryptkeeper** [comment]
This is a known issue, I'm looking into seeing how I can work around it.

**Comment by Cryptkeeper** [comment]
Fixed in https://github.com/Cryptkeeper/Minetrack/pull/181/commits/084790a3ba7c6dceee8ea86205f494325419b62a as part of release 5.5.1. You'll want to watch https://github.com/Cryptkeeper/Minetrack/pull/181 for it's release (should be today).

Thanks for the bug report!
