### ISSUE TITLE
Graph update kicks out of the zoomed view

### ISSUE THREAD

**Issue by isokissa3** [Cryptkeeper/Minetrack#185]
When the graph gets update it kicks you out of the zoomed view. This is quite annoying when trying to closely inspect graphs that show more than just one day.

**Comment by Cryptkeeper** [comment]
Fixed in https://github.com/Cryptkeeper/Minetrack/pull/181/commits/6aeb8b5045176cb1b2eacaee3801413c002ac82c as part of release 5.5.1. You'll want to watch #181 for its release (should be today). This fix is a bit of a hack, so it might break under pressure 😉 

Thanks for the bug report!
