### ISSUE TITLE
servers with a constant player count will fail to render graphs

### ISSUE THREAD

**Issue by Cryptkeeper** [Cryptkeeper/Minetrack#188]
This is caused by the RelativeScale method calls returning the same value for min/max. RelativeScale method returns should be modified to ensure the values have _some_ offset regardless of value input.

**Comment by leeoniya** [comment]
any reason why you override the default behavior? uPlot handles this case already. and exposes its ranging function if you need to tweak it further:

https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts#L106

**Comment by Cryptkeeper** [comment]
Fixed in https://github.com/Cryptkeeper/Minetrack/commit/7b1496511f0a07e87419741bb770f7dcb9814432

@leeoniya I wrote my own originally since I couldn't find a nice place to tap into that sort of logic, but rangeNum should work. I'll work on porting the logic in another version. Thanks!
