### ISSUE TITLE
Minetrack: Lost connection

### ISSUE THREAD

**Issue by SquareCodeFX** [Cryptkeeper/Minetrack#189]
Webserver Nginx
Server version Ubuntu 20.04

When I try to go to the website it only says: Minetrack lost connection, Reconnect in ...seconds
Does anyone know what this could be and how I can fix it?

Log:
1:40:30 PM 6/18/2020 - info: Started on 0.0.0.0:1337
1:40:30 PM 6/18/2020 - warn: No SRV records were resolved for VaceMC.net. Minetrack will skip attempting to resolve VaceMC.net SRV records for 60 minutes.
1:40:30 PM 6/18/2020 - warn: No SRV records were resolved for mc.Hypixel.net. Minetrack will skip attempting to resolve mc.Hypixel.net SRV records for 60 minutes.
1:40:32 PM 6/18/2020 - info: 127.0.0.1 requested: /
1:40:34 PM 6/18/2020 - info: 127.0.0.1 requested: /
1:40:34 PM 6/18/2020 - info: 127.0.0.1 requested: /main.717770f8.css
1:40:34 PM 6/18/2020 - info: 127.0.0.1 requested: /main.2d318953.js
1:40:34 PM 6/18/2020 - info: 127.0.0.1 requested: /logo.ee1f81b9.svg
1:40:34 PM 6/18/2020 - info: 127.0.0.1 requested: /
1:40:34 PM 6/18/2020 - info: 127.0.0.1 requested: /logo.ee1f81b9.svg
1:40:35 PM 6/18/2020 - info: 127.0.0.1 requested: /
1:40:39 PM 6/18/2020 - info: 127.0.0.1 requested: /

**Comment by hugmanrique** [comment]
Please open your browser devtools and share the console logs; is any error appearing? Are you running behind a reverse Nginx/Apache proxy?

**Comment by SquareCodeFX** [comment]
Web log http://prntscr.com/t213k2
my nginx config: https://paste.squarecode.de/8DYCA07zCR

**Comment by hugmanrique** [comment]
You need to add some extra proxy options to the `location /` block. See https://github.com/Cryptkeeper/Minetrack/issues/167#issuecomment-629714656

**Comment by SquareCodeFX** [comment]
Can you send me exactly what I need in there? Don't know my way around it.

**Comment by hugmanrique** [comment]
```conf
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;

	server_name stats.squarecode.de;
	
	ssl on;
  ssl_certificate /etc/letsencrypt/live/squarecode.de/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/squarecode.de/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/squarecode.de/fullchain.pem;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 SSLv2 SSLv3;
  ssl_ciphers HIGH:!aNULL:!MD5;
  
	# logging
	access_log /var/log/nginx/stats.squarecode.de.access.log;
	error_log /var/log/nginx/stats.squarecode.de.error.log warn;

	# reverse proxy
	location / {
		proxy_pass http://127.0.0.1:1337;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
	}

}

# HTTP redirect
server {
	listen 80;
	listen [::]:80;
	access_log off;
	server_name .stats.squarecode.de;

	location / {
		return 301 https://stats.squarecode.de$request_uri;
	}
}
```

**Comment by SquareCodeFX** [comment]
You're just a sweetheart. I'm infinitely grateful. As God is my witness
Thank you very much
