### ISSUE TITLE
log scales

### ISSUE THREAD

**Issue by leeoniya** [Cryptkeeper/Minetrack#197]
@Cryptkeeper 

log scales...coming to a uPlot near you. same data (today's cloudflare outage):

**linear**

![linear-cloudflare](https://user-images.githubusercontent.com/43234/87843432-57091600-c87a-11ea-876e-69fd26a07f31.png)

**logarithmic**
![log-cloudflare](https://user-images.githubusercontent.com/43234/87843431-57091600-c87a-11ea-8265-26a70db825f8.png)

**Comment by SWinxy** [comment]
Could this be implemented in the current graphing system?

**Comment by leeoniya** [comment]
log scale capability landed in uPlot `master` a few days ago, but it will be a couple weeks before i cut a new uPlot release since there's more stuff to finish up. if @Cryptkeeper wants to use a pre-release version until then, it should be possible.

i've added an interactive version of the above charts to uPlot's demos: https://leeoniya.github.io/uPlot/demos/log-scales.html

**Comment by leeoniya** [comment]
1.1.0 is out with log scale support

**Comment by Cryptkeeper** [comment]
Closing this issue since I have this tracked on a project board. Thanks!
