### ISSUE TITLE
[QUESTION] How do i ping specific servers

### ISSUE THREAD

**Issue by Laukage** [Cryptkeeper/Minetrack#200]
Minetrack can't reach a server with a subdomain + a different port than 25565.

how is this achieveable?

**Comment by hugmanrique** [comment]
You can add a `port` property to each server entry on the `servers.json` file.

**Comment by Laukage** [comment]
Is there a documentation somewhere that includes everything you can do with it and such?

**Comment by hugmanrique** [comment]
Unfortunately not. However, most settings are self-explanatory. Feel free to post your questions here.

**Comment by Laukage** [comment]
How do i enable this?
![image](https://user-images.githubusercontent.com/46964809/89048709-7d39b600-d350-11ea-9289-0f1f60aacc60.png)

and how do i fix the "Sessions is offline"?

**Comment by hugmanrique** [comment]
For the former, enable `logToDatabase` on the `config.json` file. The latter is an issue Mojang needs to fix, see #177 for more details.

**Comment by Laukage** [comment]
Ah sweet, that basically solved ally my questions 👍
