### ISSUE TITLE
Mojang session server

### ISSUE THREAD

**Issue by Laukage** [Cryptkeeper/Minetrack#209]
Hi, as i've been using minetrack for awhile and know that session check has been offline for quite some time - i created a ticket last time where i was told their session server api got removed.

I am a part of syscraft discord, and they a have discord bot checking "sessionserver.mojang.com" and it seems to be working as intended - maybe this is a solution to minetrack aswell? :)

EDIT:
After looking through the minetrack code, i see that it is indeed that server that is being used, so it the method of pinging it that doesn't work i would assume or am i wrong?

**Comment by Cryptkeeper** [comment]
It's because Mojang's status endpoint, https://status.mojang.com/check, continually reports the service as "red" status (offline). Why? I don't know.
