### ISSUE TITLE
Keep getting "Cannot GET /" error on the site

### ISSUE THREAD

**Issue by tarna** [Cryptkeeper/Minetrack#214]
I cloned the repository to something called repl.it and that is where I'm running the project. And when I run it, the code runs fine with no errors but on the site it creates, it just says "Cannot GET /" on it. And the console also gets spammed with the following.
![image](https://user-images.githubusercontent.com/46247728/98628199-06637000-22e4-11eb-8324-b9543d797b9f.png)

I am not sure how to fix it since I cloned the repository exactly. And sorry if this is the wrong place to ask something like this.

**Comment by Cryptkeeper** [comment]
I'm assuming your Minetrack installation doesn't have a `dist` folder (or it's empty). You need to run step 5 described at https://github.com/Cryptkeeper/Minetrack#installation to generate the website's bundled HTML/CSS/Javascript assets.

The errors in your screenshot (where it says "Socket timeout") just means it wasn't able to complete the ping within the default 3 second timeout. You can adjust the value in `config.json` (see https://github.com/Cryptkeeper/Minetrack/blob/master/config.json#L9)
