### ISSUE TITLE
Error by starting main

### ISSUE THREAD

**Issue by ThugJarno** [Cryptkeeper/Minetrack#220]
![image](https://user-images.githubusercontent.com/73259075/103578465-e9f44600-4ed6-11eb-8a11-a77d1ba483f7.png)

**Comment by hugmanrique** [comment]
You're most likely running an ancient (unsupported) Node version. Minetrack requires v12.4.0+, and the current LTS is recommended. You can check your version with `node -v`

**Comment by hugmanrique** [comment]
`sudo` might be using a different path (https://superuser.com/questions/709515/command-not-found-when-using-sudo) and thus a different `node` binary. Minetrack itself doesn't require root privileges (in fact, doing so is insecure). If you want to bind Minetrack on a privileged port, reverse proxy it through Nginx, Apache, etc.

**Comment by ThugJarno** [comment]
![image](https://user-images.githubusercontent.com/73259075/103679924-c4724580-4f85-11eb-8541-14eff692dcfe.png)

**Comment by hugmanrique** [comment]
The SQLite dependency cannot find itself, does `npm install` (no sudo) return successfully? If so, try starting Minetrack again. If this doesn't fix it, I suspect this might be a permissions-related issue. Try cloning Minetrack on your home dir.

**Comment by ThugJarno** [comment]
![image](https://user-images.githubusercontent.com/73259075/103891736-a96d1600-50ea-11eb-8a76-9f58881e7b92.png)
![image](https://user-images.githubusercontent.com/73259075/103891767-b558d800-50ea-11eb-8bdb-e054ea9fa70e.png)
NPM audit fix doesn't fix it.

**Comment by hugmanrique** [comment]
There's some potential fixes on their repo: try https://github.com/mapbox/node-sqlite3/issues/906#issuecomment-438140503, https://github.com/mapbox/node-sqlite3/issues/906#issuecomment-743347489, (other) in that order, while checking if the app starts after each solution.

**Comment by ThugJarno** [comment]
Thanks it works! Next problem...

![image](https://user-images.githubusercontent.com/73259075/104007953-08916000-51a9-11eb-84a1-16a769799a9e.png)

**Comment by ThugJarno** [comment]
I'm using apache2. I tried something. New error.
![image](https://user-images.githubusercontent.com/73259075/104013719-22837080-51b2-11eb-96af-74efe4165cd2.png)
![image](https://user-images.githubusercontent.com/73259075/104013743-2d3e0580-51b2-11eb-9f56-0c87b5e56cd8.png)

**Comment by hugmanrique** [comment]
https://github.com/Cryptkeeper/Minetrack/issues/194

**Comment by ThugJarno** [comment]
Thanks for you fast reply. But it doesn't work for me.
![image](https://user-images.githubusercontent.com/73259075/104034832-b153b580-51d1-11eb-84db-e8cb475d56b1.png)
![image](https://user-images.githubusercontent.com/73259075/104035230-2f17c100-51d2-11eb-8e61-6fb1b6633ffc.png)

**Comment by hugmanrique** [comment]
You're not supposed to serve Minetrack files directly (you're currently exposing your config files publicly). Move the Minetrack directory to your home dir, and setup the Apache virtual host as a reverse proxy to the Minetrack address (running on another port) as the previously mentioned issue suggests. Your config doesn't look like it, so that's why it isn't working. Minetrack runs its own HTTP and WebSocket server.

**Comment by ThugJarno** [comment]
Is HTTPS needed?

**Comment by hugmanrique** [comment]
Minetrack doesn't provide HTTPS support, but your Apache/Nginx/Cloudflare proxy can add/require HTTPS support.

**Comment by ThugJarno** [comment]
I'm stuck for days...

![image](https://user-images.githubusercontent.com/73259075/104298480-51f0f080-54c4-11eb-80bd-5a7c16fd2bb9.png)
![image](https://user-images.githubusercontent.com/73259075/104298508-587f6800-54c4-11eb-9d04-79ce77e5cf2b.png)
