### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by rtm516** [Cryptkeeper/Minetrack#226]
Could you register the Dockerfile with an online service so I can just pull it down and don't have to build it everytime the repo updates?
If you cant use the official docker site then quay.io works nicely, even GitHub has their own container registry which should work.

**Comment by nothub** [comment]
To make sure the resulting image is based on an updated node image, it would have to be rebuilt in a regular interval that is not solely triggered by git interactions, in case there is a time of inactivity.

**Comment by hugmanrique** [comment]
GitHub Actions support cronjobs, so that's a possible solution.

**Comment by rtm516** [comment]
As a temp solution I have it building on my CI and pushing to dockerhub. It checks hourly for git changes and builds if there is any, and it also builds weekly incase node has updated. Only builds for amd64.
https://hub.docker.com/r/rtm516/minetrack

**Comment by Cryptkeeper** [comment]
Closing to move discussion to https://github.com/Cryptkeeper/Minetrack/pull/227
