### ISSUE TITLE
How would I see a graph of a certain server from a specific time period

### ISSUE THREAD

**Issue by AsksTooManyQuestions** [Cryptkeeper/Minetrack#231]
Hello there.

I installed MineTrack on my server a while ago, and I would like to know how I could see the playercount from a certain time period, as I cannot see it anywhere on the page.

**Comment by hugmanrique** [comment]
Have you enabled the `logToDatabase` option in your `config.json`? If so, the big graph should appear. You can then unselect all servers and select the specific one you want to see.

If you meant to check for a specific time interval out of all logged player counts, this isn't currently possible. However, the SQLite file has all the data you need and you can query the file yourself. The table schema is `CREATE TABLE IF NOT EXISTS pings (timestamp BIGINT NOT NULL, ip TINYTEXT, playerCount MEDIUMINT)`
