### ISSUE TITLE
Update Parcel

### ISSUE THREAD

**Issue by DEVTomatoCake** [Cryptkeeper/Minetrack#234]
Please update parcel to v2 as I got random the error in [#5943](https://github.com/parcel-bundler/parcel/issues/5943) and no fix really worked for me, after I updated parcel and other depencies by myself minetrack starts again, but the page dont load, it only says Connecting...

**Comment by hugmanrique** [comment]
This issue should be fixed now (see https://github.com/parcel-bundler/parcel/issues/5943#issuecomment-799899064). Nonetheless I agree we should move to v2 whenever it gets release (the latest version is a beta). However, imo this is a low priority issue.

**Comment by Cryptkeeper** [comment]
Moving discussion to https://github.com/Cryptkeeper/Minetrack/pull/237
