### ISSUE TITLE
Other types of pings?

### ISSUE THREAD

**Issue by Laukage** [Cryptkeeper/Minetrack#249]
Hi, some servers are disabling icmp so i wanna know if it possible to change which type of "ping" it uses to grab player count, ex minecraft-mp is able to get data from the same servers

Firstly i thought they blocked my IP, but thats not the case cuz i am able to ping the IP from the node itself.

**Comment by hugmanrique** [comment]
Minetrack doesn't use ICMP to "ping" the servers. Instead, it creates a TCP socket to talk to the Minecraft server following the vanilla protocol (see wiki.vg for details).
