### ISSUE TITLE
Apache2 Reverse proxy

### ISSUE THREAD

**Issue by That-Guy-Jack** [Cryptkeeper/Minetrack#250]
![image](https://user-images.githubusercontent.com/56127525/117503458-e4883480-af78-11eb-9759-396ecaeda030.png)
![image](https://user-images.githubusercontent.com/56127525/117503479-e94ce880-af78-11eb-8e96-1fc6df955a65.png)
 what are the correct Reverse proxy rules for apache i can see the ones  for nginx but can't seem to find onse that work for apache2

**Comment by hugmanrique** [comment]
See #194

**Comment by That-Guy-Jack** [comment]
just tried two different configs but non of them work each location is inside of a normal https vhost

config 1:
```
    <Location "/minecraft/online/" >
        ProxyPreserveHost On
    	ProxyPass "http://192.168.1.90:8888/"
    	ProxyPassReverse "http://192.168.1.90:8888/"
		RewriteCond %{HTTP:Upgrade} =websocket
		RewriteRule /(.*) ws://192.168.1.90:8888/$1 [P,QSA,L]
		RewriteCond %{HTTP:Upgrade} !=websocket
		RewriteRule /(.*) http://192.168.1.90:8888/$1 [P,QSA,L]
		RequestHeader set X-Forwarded-Port "443"
		RequestHeader set X-Forwarded-Proto "https"
        RewriteEngine on
    </Location>
```

config 2:
```
    <Location "/minecraft/online/" >
		RewriteCond %{HTTP:Upgrade} =websocket
		RewriteRule /(.*) ws://192.168.1.90:8888/$1 [P,QSA,L]
		RewriteCond %{HTTP:Upgrade} !=websocket
		RewriteRule /(.*) http://192.168.1.90:8888/$1 [P,QSA,L]
		RequestHeader set X-Forwarded-Port "443"
		RequestHeader set X-Forwarded-Proto "https"
        RewriteEngine on
    </Location>
```

**Comment by Cryptkeeper** [comment]
We recommend using nginx with the provided configuration, and don't provide any support for helping configure apache2 instances. Best of luck.
