### ISSUE TITLE
Add new community instance

### ISSUE THREAD

**Issue by HerrSammyDE** [Cryptkeeper/Minetrack#251]
Hello,

could you maybe add my website to the [readme](https://github.com/Cryptkeeper/Minetrack#community-showcase)?
-> https://www.minecraft-stats.de/

Best regards

**Comment by MiniDigger** [comment]
you should open a pullrequest to add that :)
(see https://github.com/Cryptkeeper/Minetrack/pull/247/as an example)

**Comment by HerrSammyDE** [comment]
> you should open a pullrequest to add that :)
> (see #247 an example)

Oh, thanks for the information!
