### ISSUE TITLE
Offline Server Disrupts Displaying Remaining Servers

### ISSUE THREAD

**Issue by falceso** [Cryptkeeper/Minetrack#257]
# Information
**Version:** 5.5.9
**Servers Monitoring:** Hypixel, HiveMC, OfflineServer, Mineplex, and CubeCraft. - [servers.json](https://gist.github.com/falceso/f06ec65c70cd3beab9b50f52c6cbc5b2#file-servers-json)
**Browser Used:** Chrome and Firefox
[DevTools Console](https://gist.github.com/falceso/f06ec65c70cd3beab9b50f52c6cbc5b2#file-devtoolsconsole-txt)
**Possible References:** #253 af2301495ec015efdbc994391c0732db2d5df19c
**Install:** Using self-created Docker Container w/ Manual NPM Install Instructions

# Issue
When one server is offline, the servers remaining servers underneath are no longer rendered. As seen in the below screenshot, Mineplex and CubeCraft do not show up.
![qWWvdjdCQQiwi2d](https://user-images.githubusercontent.com/10911217/120753466-0fa26d00-c4c0-11eb-8871-c1928595309d.png)

# Temporary Workaround 
Move the Offline Server to the bottom of the server.json and less servers interrupted in the rendering process, the remaining server above have for the most part loaded in fine.
![YCqperpBSSEnnqD](https://user-images.githubusercontent.com/10911217/120755406-cacc0580-c4c2-11eb-87cc-68d89ee6eb38.png)

**Comment by falceso** [comment]
**Adding to the above issue.** 
It appears the offline server additionally breaks the pinging of (all?) servers, as the player count gets stuck when graphed, "_Counting X players on X Minecraft servers_" isn't rendering the correct values, and the Mojang Sockets stop updating in the Panel.
![A2j5sRuVzmqU4Vg](https://user-images.githubusercontent.com/10911217/120914308-41e3d400-c652-11eb-9563-8ea9ae4120d7.png)

**Comment by Cryptkeeper** [comment]
Looks to be a regression from my changes in 5.5.9

**Comment by Cryptkeeper** [comment]
Fixed in https://github.com/Cryptkeeper/Minetrack/commit/0f297b72a88e7c49bda75dbac9a1ade8a8031cda, update to version 5.6.0
