### ISSUE TITLE
Graph Controller not showing

### ISSUE THREAD

**Issue by PleaseInsertNameHere** [Cryptkeeper/Minetrack#267]
Hello! I'm using Minetrack 5.6.0, but the Graph Controller is not showing.

How do I fix this? Am I doing anything wrong?

**Comment by hugmanrique** [comment]
Could you open your browser's dev tools (usually accessible by pressing the F12 key) and sharing the console output when clicking the graph controls button?

**Comment by PleaseInsertNameHere** [comment]
There is no graph controls button

**Comment by hugmanrique** [comment]
Can you then share the console output nonetheless? Browser details would also be useful.

**Comment by PleaseInsertNameHere** [comment]
Do you mean the console output of the browser or Minetrack? I'm using the latest version of Brave.

**Comment by hugmanrique** [comment]
The browser's.

**Comment by PleaseInsertNameHere** [comment]
Console's output is empty..

**Comment by hugmanrique** [comment]
Have you set `logToDatabase` to `true`? Could you also share your `config.json`?

**Comment by PleaseInsertNameHere** [comment]
Sure, this is my config.yml
```
{
	"site": {
		"port": (wont show that one),
		"ip": "0.0.0.0"
	},
	"rates": {
		"updateMojangStatus": 5000,
		"mojangStatusTimeout": 3500,
		"pingAll": 3000,
		"connectTimeout": 2500
	},
	"logFailedPings": false,
	"logToDatabase": false,
	"graphDuration": 86400000,
	"serverGraphDuration": 180000
}
```

**Comment by PleaseInsertNameHere** [comment]
Alright, thanks. I've enabled `logToDatabase` now.

Everything works fine now, have a great day!
