### ISSUE TITLE
Toggle Controls Problem

### ISSUE THREAD

**Issue by Envici** [Cryptkeeper/Minetrack#27]
When toggling the graph controls to open, the y axis markers on the per server graphs disappear. Here is a gif of the issue: 

![Image](https://i.gyazo.com/6e7daa56096acb800721fc8bf5eb3626.gif)

Thanks!

**Comment by theminecoder** [comment]
@Envici Is this an issue anymore on the latest updates?

**Comment by Envici** [comment]
@theminecoder Yes, it still seems to be a problem.

**Comment by Envici** [comment]
@Cryptkeeper Just reminding that this is still an issue after the latest commits.
