### ISSUE TITLE
socket.js:14 WebSocket connection to 'ws://track.wreeper.top/' failed:

### ISSUE THREAD

**Issue by Wreeper** [Cryptkeeper/Minetrack#271]
I get this error when browsing the reversed proxy website after creating reverse proxy in apache but i wonder why?
As i can see it requests a file from /assets but both the main server that Minetrack started and Apache cannot find the /assets folder and neither can the file

**Comment by hugmanrique** [comment]
Please read https://github.com/Cryptkeeper/Minetrack/issues/250#issuecomment-913051479
