### ISSUE TITLE
Apache Proxy isn't working

### ISSUE THREAD

**Issue by OhaDerErste** [Cryptkeeper/Minetrack#272]
Every time, I'm trying to Acess the Website, i just get a disconnect Error!
Only thing i changed is the Port

Video:
https://cdn.ohaa.xyz/Cub_8714.mp4

Apache Config:
https://paste.ohaa.xyz/emehakucih.apache

Main Site works
http://160.20.145.158:8081

Over the Proxy not:
https://mcstats.ohaa.xyz

**Comment by hugmanrique** [comment]
Please see https://github.com/Cryptkeeper/Minetrack/issues/250#issuecomment-913051479. You can try the suggestions there though.

**Comment by OhaDerErste** [comment]
> Please see [#250 (comment)](https://github.com/Cryptkeeper/Minetrack/issues/250#issuecomment-913051479). You can try the suggestions there though.

Thx
