### ISSUE TITLE
Graph not showing

### ISSUE THREAD

**Issue by IuCC123** [Cryptkeeper/Minetrack#279]
Hello, I am noticing that my graph is not showing in any way, I'm not sure if this is an bug or if there is some way to enable it. I really want to see my graph but it does not show sadly, 

Here is how it looks like:
![image](https://user-images.githubusercontent.com/80768059/141832720-c3be9c30-a7a0-456d-a151-8f231797a8c8.png)

**Comment by hugmanrique** [comment]
Make sure you've enabled the [`logToDatabase`](https://github.com/Cryptkeeper/Minetrack/blob/main/config.json#L11) option in the `config.json` file.
