### ISSUE TITLE
Ssl

### ISSUE THREAD

**Issue by Jcodeerd** [Cryptkeeper/Minetrack#299]
Hi, is there any tutorial to setup ssl on minetrack?

**Comment by hugmanrique** [comment]
We recommend configuring e.g. [Nginx as a reverse proxy](https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/) (see the [README](https://github.com/Cryptkeeper/Minetrack#nginx-reverse-proxy) file for the initial `server` block).
