### ISSUE TITLE
i don't understand how to install the thing

### ISSUE THREAD

**Issue by PorcooDio** [Cryptkeeper/Minetrack#301]
i am not that good on programming and stuff, and so i dont' understand shat i should do with cmd

**Comment by PorcooDio** [comment]
can someone help me installing this thing?

**Comment by hugmanrique** [comment]
Please follow the [installation steps](https://github.com/Cryptkeeper/Minetrack#installation). For any specific problems, reply to this issue.

**Comment by PorcooDio** [comment]
i already tryied, but i don't understand what to do, do i have to donwload the file?

**Comment by PorcooDio** [comment]
and i don't understant what i should do on step 4, 5 and 6, i don't knwo what commands i should do on the cmd, i have installed npm only for this thing so i never used it

**Comment by hugmanrique** [comment]
You can download the latest version of Minetrack as a ZIP file from https://github.com/Cryptkeeper/Minetrack/archive/refs/heads/main.zip. For now, you can ignore the `config.json` file, the default settings are fine for a temporary setup. To run `npm`, open a terminal (as you did with `cmd`), navigate to the directory where you extracted the aforementioned ZIP file, and type the given commands (to navigate). If you get some errors, check the Node installation is correct (`npm` is included with Node.js by default). The Minetrack instance should now be accessible at `http://localhost:8080`.

**Comment by PorcooDio** [comment]
where can i find the commands?

**Comment by hugmanrique** [comment]
Those are steps 4, 5 and 6 [here](https://github.com/Cryptkeeper/Minetrack#installation).

**Comment by PorcooDio** [comment]
I dont understand them

Il dom 26 giu 2022, 2:11 AM Hugo Manrique ***@***.***> ha
scritto:
