### ISSUE TITLE
12h to 24h

### ISSUE THREAD

**Issue by Azurz** [Cryptkeeper/Minetrack#308]
Hello, I wanted to change the time format from 12h to 24h I followed this issue https://github.com/Cryptkeeper/Minetrack/issues/273 the problem is that it does not change anything 

![image_2022-07-21_133824218](https://user-images.githubusercontent.com/35930914/180204753-c3ae7c4f-ed63-4c3b-a8b0-98ef2dc99747.png)
![image_2022-07-21_133841008](https://user-images.githubusercontent.com/35930914/180204800-bacea648-a081-4a81-9175-4242a75b4933.png)

**Comment by hugmanrique** [comment]
You also need to customize the time label for the value with duration 3600: instead of `{h}{aa}`, you want `{h}`. See the [uPlot documentation](https://github.com/leeoniya/uPlot/tree/master/docs#axis--grid-opts) for the meaning of each entry.
