### ISSUE TITLE
Reset Lifeboat's record (On the Minetrack Bedrock website)

### ISSUE THREAD

**Issue by ClydeplayzYT590** [Cryptkeeper/Minetrack#315]
Lifeboat gained 250,000 players online record in just a second and its unbelievable because you cant have 100k players on your server in just a second and this will just confuse new users on the site

![20220915_195221_edited](https://user-images.githubusercontent.com/86055764/190400821-58f80037-9099-453e-b6fd-38e2fee0a48a.jpg)

**Comment by ClydeplayzYT590** [comment]
Looks like it got reset

**Comment by ClydeplayzYT590** [comment]
and looks like it just happened again
![20220921_070917_edited](https://user-images.githubusercontent.com/86055764/191389877-e7736fa5-7155-4ac6-85db-f6b0df66eaaf.jpg)

**Comment by Cryptkeeper** [comment]
Reset again, please re-open if needed.
