### ISSUE TITLE
Category arrangement seems quite arbitrary

### ISSUE THREAD

**Issue by minecrafter** [Cryptkeeper/Minetrack#32]
Just as examples:

* Wynncraft is mentioned as a "major network" but in terms of player count it would probably be more accurate to call it a mid-sized network. (To be fair, as an MMORPG, average time spent is a lot higher on Wynncraft compared to its minigame peers.)
* PartyZone is mentioned as a "small network" but would probably be more accurately classified as a mid-sized network in terms of player count.

Clear categorization rules would be useful to prevent confusion.

**Comment by Cryptkeeper** [comment]
They're left over from the original integration of them into the system. I'm planning to remove them from production shortly.

**Comment by Cryptkeeper** [comment]
Removed from production.
