### ISSUE TITLE
Tracket not working using Proxied Cloudflare

### ISSUE THREAD

**Issue by apatuka** [Cryptkeeper/Minetrack#338]
Hello,

I setup a ProxyReverse on Apache2 and added a DNS record with Proxied mode on Cloudflare, but it's not working
Can't stablish connection wss://*******/ 

What do i need to enable this ?

**Comment by hugmanrique** [comment]
Cloudflare provides an option to enable WebSocket connections; see https://support.cloudflare.com/hc/en-us/articles/200169466-Using-Cloudflare-with-WebSockets for how to enable them. I can't guarantee this will work, but we've had success in the past https://github.com/Cryptkeeper/Minetrack/issues/291#issuecomment-1059934621)
