### ISSUE TITLE
Remove Pixel Paradise (when the time comes)

### ISSUE THREAD

**Issue by 1unar-Eclipse** [Cryptkeeper/Minetrack#356]
Recently, Pixel Paradise's Discord and Twitter announced that the server would be closing around next week.

![image](https://github.com/Cryptkeeper/Minetrack/assets/74077800/13241eda-441d-4bc0-a97c-3f191774b81e)

**Comment by Cryptkeeper** [comment]
Looks like it was postponed without a new date. Feel free to re-open if anything changes.
