### ISSUE TITLE
[Suggestion] Add Server EterCube

### ISSUE THREAD

**Issue by ArcadeProgram** [Cryptkeeper/Minetrack#358]
We are a french pvp faction and cross plateform server, with an average of 20 players (it's not a lot, but more than some server in the list).

If you can add us, it will be very nice, thank you in advance ^^

**Comment by ArcadeProgram** [comment]
Excuse me, I have renamed my account, so server is named Etercube:
- website: https://etercube.fr
- IP: mc.etercube.fr (défaut port 25565 for java)

**Comment by Cryptkeeper** [comment]
Unfortunately, I'm unable to add it at this time given the player count - best of luck on your network! :)

**Comment by ArcadeProgram** [comment]
But their is servers in your minetrack with less players than us
And their is also inactives servers.

So it would be very nice if you add us :)
