### ISSUE TITLE
Remove Pixel Paradise

### ISSUE THREAD

**Issue by 1unar-Eclipse** [Cryptkeeper/Minetrack#363]
The new shutdown date is today, about 50 minutes from time of posting.

(Repost of #356 as I don't have reopen perms)

**Comment by 1unar-Eclipse** [comment]
Update from their Discord: ![image](https://github.com/Cryptkeeper/Minetrack/assets/74077800/ab62cd7a-3538-4cb6-a1f1-cab9e64820c4)

**Comment by 1unar-Eclipse** [comment]
It is gone.
![image](https://github.com/Cryptkeeper/Minetrack/assets/74077800/80e4f004-2778-4de4-ac5b-d3a948aa2535)

**Comment by DarkVibes2022** [comment]
#364 resolves this issue

**Comment by Cryptkeeper** [comment]
Merged #364. Thanks for the heads up and PRs folks.
