### ISSUE TITLE
Request - Make Dragonapi compatible

### ISSUE THREAD

**Issue by formerlyknownasprince** [Cryptkeeper/Minetrack#42]
We're using a custom build of this for us, and we've run into a problem that it can't properly track if we have the dragonapi mod installed.

**Comment by Cryptkeeper** [comment]
What's the DragonAPI?

How is it incompatible specifically?

**Comment by formerlyknownasprince** [comment]
its a coremod @ReikaKalseki

**Comment by ReikaKalseki** [comment]
DragonAPI is a base mod for a dozen others. Though it has ASM and modifies the base code in some 60 places, the much larger potential source of issues is Forge, which it is built upon. I have no idea what Minetrack is or does; it is Forge-compatible? If not, what do you mean, "can't properly track"? ASM usually crashes with a ClassFormat or VerifyError, and a Forge incompatibility would probably manifest as a simple NoClassDefFound or Minetrack being ignored entirely.

**Comment by Cryptkeeper** [comment]
Minetrack never touches the actual servers. Assuming there's no issues with a vanilla client pinging the server, Minetrack should be fine.

Are you sure @formerlyknownasprince that you've correctly configured the servers in config.json?

**Comment by formerlyknownasprince** [comment]
So in other words it's reka's fault again? wow, didn't see that one coming. why do i use your mods again...oh right because you put code in them to corrupt worlds for removing them. asshole.

**Comment by Cryptkeeper** [comment]
Please stay on topic and be nice, otherwise I'm just going to close the issue.

**Comment by formerlyknownasprince** [comment]
You haven't had to deal with all the problems people using his mods have to put up with. the time for being nice is past.

**Comment by ReikaKalseki** [comment]
> You haven't had to deal with all the problems people using his mods have to put up with

You mean the ones cause by user stupidity, likely including this one? You have already been told, *by the developer of the tool you claim is having issues*, that your error is nonsensical and that the only plausible explanation is that it is of your own creation. Unless you want to start sounding like [this guy](https://github.com/lawremi/PerFabricaAdAstra/issues/56#issuecomment-220864276) and argue with a developer as if you know their own code better than them, looking like an idiot all the while, I suggest you start listening to the information you are given, check your configuration settings, verify that it does indeed happen *only and always* with DragonAPI, and in general rely on reason more than than instinct.

>  because you put code in them to corrupt worlds for removing them

You mean the Forge bug that I tried to have them fix (and was summarily ignored), and have a fix for [on the front page in my site, with an explanation detailed in bold](https://sites.google.com/site/reikasminecraft/home)? The one for which the only complaints are from people too lazy or incompetent to comprehend or follow the instructions, and which usually manifest as a paragraph of useless drivel?

**Comment by FurryDJ** [comment]
Good day @formerlyknownasprince Reika and I regret to inform you we've not the slightest idea of what you're talking about. Automatically assigning blame and refusing to further evaluate is the number one way to cease any form of cooperation. If you wish to make empty defamatory statements and spread slander I'd recommend not doing it on other people's hubs. Thank you. If this is indeed a legitimate misunderstanding or the work of ignorance we implore you to report the issue over at Reika's bug tracking hub.
