### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by opkiler22789** [Cryptkeeper/Minetrack#54]
root@vk2271504881:~/web# npm install
-
> sqlite3@3.1.1 install /root/web/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: Нет такого файла или каталога
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the sqlite3@3.1.1 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/web
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/web/npm-debug.log
npm ERR! not ok code 0

Please, help

**Comment by opkiler22789** [comment]
Soory, Pless close

**Comment by MiniDigger** [comment]
you can close it yourself @opkiler22789
