### ISSUE TITLE
Combination Graph not showing

### ISSUE THREAD

**Issue by Kashalls** [Cryptkeeper/Minetrack#61]
I found that running the node.js "app.js" and opening the site in an browser shows no graph and I believe it is due to no SSL/TLS. Is there a recommended way to add this through Node.JS or a way to incorporate this into a NGINX Web Server on Linux? Thanks

**Comment by Kashalls** [comment]
Did some snooping and found that http can be changed to https in /lib/server.js at the near top.

**Comment by Envici** [comment]
@Kashalls if you're talking about the large graph, have you got log to database enabled in the config?

**Comment by Kashalls** [comment]
Yes,  I figured there was something I was missing!

*Jordan J.*
jordpjones@gmail.com
https://jordanj.tech

*Altaris Nine Director*
jordan@altarisnine.com
https://altarisnine.com
