### ISSUE TITLE
Help sqllite3 not install

### ISSUE THREAD

**Issue by maxim19116** [Cryptkeeper/Minetrack#62]
[root@makscraft Minetrack]# npm install sqlite3

> sqlite3@3.1.1 install /home/Minetrack/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

make: Вход в каталог `/home/Minetrack/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
Release/obj.target/deps/action_before_build.stamp { dev: 64768,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 1679111,
  size: 0,
  blocks: 0,
  atime: 2017-01-28T21:55:46.000Z,
  mtime: 2017-01-28T21:55:46.000Z,
  ctime: 2017-01-28T21:55:46.814Z,
  birthtime: 2017-01-28T21:55:46.814Z }
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o
./Release/.deps/Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o.d.raw { dev: 64768,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 1679115,
  size: 146,
  blocks: 8,
  atime: 2017-01-28T21:56:17.000Z,
  mtime: 2017-01-28T21:56:17.000Z,
  ctime: 2017-01-28T21:56:17.493Z,
  birthtime: 2017-01-28T21:56:17.493Z }
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../node_modules/nan/nan.h:194:0,
                 from ../src/database.h:10,
                 from ../src/database.cc:4:
../node_modules/nan/nan_maybe_43_inl.h: В функции «Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)»:
../node_modules/nan/nan_maybe_43_inl.h:221:58: предупреждение: «v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)» is deprecated (declared at /root/.node-gyp/6.9.1/include/node/v8.h:3031): Cloning is not supported. [-Wdeprecated-declarations]
   return array->CloneElementAt(GetCurrentContext(), index);
                                                          ^
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:200,
                 from ../src/database.h:10,
                 from ../src/database.cc:4:
../node_modules/nan/nan_implementation_12_inl.h: In static member function «static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)»:
../node_modules/nan/nan_implementation_12_inl.h:40:38: предупреждение: «static v8::Local<v8::Value> v8::BooleanObject::New(bool)» is deprecated (declared at /root/.node-gyp/6.9.1/include/node/v8.h:4007): Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from ../src/database.h:10:0,
                 from ../src/database.cc:4:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:602:20: ошибка: переменная или поле «AddGCEpilogueCallback» объявлено void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../node_modules/nan/nan.h:602:7: ошибка: «GCEpilogueCallback» не является элементом «v8::Isolate»
       v8::Isolate::GCEpilogueCallback callback
       ^
../node_modules/nan/nan.h:603:18: ошибка: expected primary-expression before «gc_type_filter»
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:608:20: ошибка: переменная или поле «RemoveGCEpilogueCallback» объявлено void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../node_modules/nan/nan.h:608:7: ошибка: «GCEpilogueCallback» не является элементом «v8::Isolate»
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../node_modules/nan/nan.h:613:20: ошибка: переменная или поле «AddGCPrologueCallback» объявлено void
       v8::Isolate::GCPrologueCallback callback
                    ^
../node_modules/nan/nan.h:613:7: ошибка: «GCPrologueCallback» не является элементом «v8::Isolate»
       v8::Isolate::GCPrologueCallback callback
       ^
../node_modules/nan/nan.h:614:18: ошибка: expected primary-expression before «gc_type_filter»
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:619:20: ошибка: переменная или поле «RemoveGCPrologueCallback» объявлено void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../node_modules/nan/nan.h:619:7: ошибка: «GCPrologueCallback» не является элементом «v8::Isolate»
       v8::Isolate::GCPrologueCallback callback) {
       ^
../node_modules/nan/nan.h: В функции «bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)»:
../node_modules/nan/nan.h:1961:16: предупреждение: «bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)» is deprecated (declared at /root/.node-gyp/6.9.1/include/node/v8.h:2750): Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
../src/database.cc: In static member function «static Nan::NAN_METHOD_RETURN_TYPE node_sqlite3::Database::New(Nan::NAN_METHOD_ARGS_TYPE)»:
../src/database.cc:132:96: предупреждение: «bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)» is deprecated (declared at /root/.node-gyp/6.9.1/include/node/v8.h:2694): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
     info.This()->ForceSet(Nan::New("filename").ToLocalChecked(), info[0].As<String>(), ReadOnly);
                                                                                                ^
../src/database.cc:133:86: предупреждение: «bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)» is deprecated (declared at /root/.node-gyp/6.9.1/include/node/v8.h:2694): Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
     info.This()->ForceSet(Nan::New("mode").ToLocalChecked(), Nan::New(mode), ReadOnly);
                                                                                      ^
../src/database.cc: In static member function «static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)»:
../src/database.cc:143:9: предупреждение: неиспользуемая переменная «status» [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function «static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)»:
../src/database.cc:227:9: предупреждение: неиспользуемая переменная «status» [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function «static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)»:
../src/database.cc:505:9: предупреждение: неиспользуемая переменная «status» [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function «static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)»:
../src/database.cc:605:9: предупреждение: неиспользуемая переменная «status» [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
make: *** [Release/obj.target/node_sqlite3/src/database.o] Ошибка 1
make: Выход из каталога `/home/Minetrack/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-514.2.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/Minetrack/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/Minetrack/node_modules/sqlite3/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /home/Minetrack/node_modules/sqlite3
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/Minetrack/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/Minetrack/node_modules/sqlite3/lib/binding/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/Minetrack/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 3.10.0-514.2.2.el7.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/home/Minetrack/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/Minetrack/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.14
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/Minetrack/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/Minetrack/node_modules/sqlite3/lib/binding/node-v48-linux-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.10.0-514.2.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "sqlite3"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/Minetrack/npm-debug.log

**Comment by Serializator** [comment]
:+1:
