### ISSUE TITLE
17:21:37 12/3/17 - error: Failed to ping mc.hypixel.net: Socket timed out when connecting to mc.hypixel.net:25565

### ISSUE THREAD

**Issue by Erdack54** [Cryptkeeper/Minetrack#68]
Hello, I install MineTrack and I have this error in lancan daemon: 17:21:37 12/3/17 - error: Failed to ping mc.hypixel.net: Socket timed out when connecting to mc.hypixel .net: 25565

(I'm french so I use a translator, sorry for my mistakes)

**Comment by Envici** [comment]
Might be a problem with your server/computer's connection to Hypixel. Does it happen with any other servers?

**Comment by hugmanrique** [comment]
Can you do a traceroute and a ping from console and share the results?

**Comment by Erdack54** [comment]
Okay, I'll send the results tonight

**Comment by Erdack54** [comment]
[http://zupimages.net/up/17/11/v9zu.png](http://zupimages.net/up/17/11/v9zu.png) & [http://zupimages.net/up/17/11/q7ed.png](http://zupimages.net/up/17/11/q7ed.png)

**Comment by Erdack54** [comment]
Problem set, I can tweak and his works, thanks for the help :)
