### ISSUE TITLE
Graphical glitch on PE site

### ISSUE THREAD

**Issue by kennethbgoodin** [Cryptkeeper/Minetrack#71]
Observed on the pocket flavor (pocket,minetrack.me). Hovering over the server % bar causes ghost text to be displayed in the main large graph, ex: https://gyazo.com/5c08c95b17fa8757b0fc87b3deb7046a

**Comment by kennethbgoodin** [comment]
Browser is chrome 56.0.2924.76 beta (64-bit)

**Comment by hugmanrique** [comment]
This feature is intended, the previous tooltip has been replaced by this slideable text bar

**Comment by kennethbgoodin** [comment]
The ghost text to the right of the graph (the 4k, 2k, etc.) is intended? It's very clear in the gif but here's a screenshot as well http://prntscr.com/ek2td3

**Comment by kennethbgoodin** [comment]
Obviously the slideable text bar is intentional, that's not what I reported.

**Comment by Cryptkeeper** [comment]
The only solution is to re-render the chart which is expensive and silly. I'll move the sliding text later tonight so it doesn't cause it, it's a bit annoying anyways 😄

**Comment by hugmanrique** [comment]
Flot.js should really learn how to manage redrawings when things change

**Comment by Cryptkeeper** [comment]
Moved the slider text into a tooltip in https://github.com/Cryptkeeper/Minetrack/commit/42c744b9ddfce127016f8258f343a92cd92f9648. CloudFlare might take a moment to invalidate.
