### ISSUE TITLE
Main graph not showing as intended

### ISSUE THREAD

**Issue by maol3** [Cryptkeeper/Minetrack#73]
I'm getting lots of errors when installing this on CentOS 7, this is the install log. http://pastebin.com/N7PkW4zK

It does work to start the application and it is running, but the main graph does not work at all.

**Comment by Cryptkeeper** [comment]
If you skip to the end of the log, sqlite didn't install properly so Minetrack is running without a database. 

You'll need to do some research for how to install sqlite3 on CentOS, a quick Google came up with this: http://serverfault.com/questions/747588/install-sqlite-latest-version-on-centos6-7
