### ISSUE TITLE
Suggestion - Custom graph colour

### ISSUE THREAD

**Issue by Votarb** [Cryptkeeper/Minetrack#75]
My suggestion is to make a graph colour into a customisable variable: settable in servers.json, just like "type" or "category".
Then you could force those colours, instead of them being assigned randomly.

**Comment by hugmanrique** [comment]
For all the British English speakers, I'm sorry for calling it color instead of colour 😝

**Comment by Votarb** [comment]
Thanks guys! Fast response much appreciated
