### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by DylanKeir** [Cryptkeeper/Minetrack#80]
`[09:23:34] root@dyl4n:~/minetrack # node app.js
9:23:55 AM 8/6/17 - info: Booting, please wait...
9:23:55 AM 8/6/17 - warn: Database logging is not enabled. You can enable it by setting "logToDatabase" to true in config.json. This requires sqlite3 to be installed.
9:23:55 AM 8/6/17 - info: Routes: /,/images/compass.png,/js/site.js,/js/util.js,/js/graph.js,/css/main.css
9:23:55 AM 8/6/17 - info: Started on 0.0.0.0:8080
buffer.js:1047
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkInt (buffer.js:1047:11)
    at Buffer.writeUInt8 (buffer.js:1093:5)
    at CustomBuffer.writeUByte (/root/minetrack/node_modules/mc-ping-updated/lib/mcpc_buffer.js:41:16)
    at CustomBuffer.writeUShort (/root/minetrack/node_modules/mc-ping-updated/lib/mcpc_buffer.js:32:14)
    at Socket.<anonymous> (/root/minetrack/node_modules/mc-ping-updated/lib/ping.js:35:19)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:10)`

This issue occurred when I downloaded the latest version and edited 'servers.json'.

**Comment by hugmanrique** [comment]
This error was caused by [mc-ping-updated](https://www.npmjs.com/package/mc-ping-updated) (line 35 of ping.js), will take a look and probably make a PR to fix it

**Comment by JiNJaProductionz** [comment]
Node: 7.2.0
NPM: 3.10.9

**Comment by hugmanrique** [comment]
Alright, those versions seem fine. What's the port you're passing for the server, it might be too large and might not fit in a short

**Comment by JiNJaProductionz** [comment]
Do you mean the port of the Minecraft server? If so, it's all default 25565.

**Comment by hugmanrique** [comment]
Can you paste your `config.json` file here? Remove the address (not the port) before doing so

**Comment by JiNJaProductionz** [comment]
`{
        "routes": {
                "/": "assets/html/index.html",
                "/images/compass.png": "assets/images/compass.png",
                "/js/site.js": "assets/js/site.js",
                "/js/util.js": "assets/js/util.js",
                "/js/graph.js": "assets/js/graph.js",
                "/css/main.css": "assets/css/main.css"
        },
        "faviconOverride": {

        },
        "site": {
                "port": 8080,
                "ip": "0.0.0.0"
        },
        "rates": {
                "upateMojangStatus": 5000,
                "mojangStatusTimeout": 3500,
                "pingAll": 3000,
                "connectTimeout": 2500
        },
        "logToDatabase": false,
        "graphDuration": 86400000,
        "serverCategories": {
                "network": "Networks"
        },
        "versions": {
                "PC": [
                        4,
                        5,
                        47,
                        107,
                        210,
                        315,
                        335
                ],
                "PE": [
                        0
                ]
        },
        "categoriesVisible": true,
        "serverTypesVisible": true
}
`
