### ISSUE TITLE
long startup(dead?) after running for a while

### ISSUE THREAD

**Issue by mechoriet** [Cryptkeeper/Minetrack#81]
My private minetracker has been running for a month or so,
and has now a database of the size 1.3GB,
and now it wont start or loading for infinite time.

it uses 100% cpu one core
and not much ssd reading

i guess its slow on the MAX(playerCount) part like that is the only part of the startup that could potentially take a while

a suggestion maybe a clean up argument so you can clean up the history to for instance 7 or 3 days

and maybe automatically every week its running from startup timestamp.

or store the record in a seperate table so it can load up faster without going thru all records to find the record

**Comment by jensz12** [comment]
I had the same issue after just 3 hours of running it.

**Comment by TNTUP** [comment]
Same issue here :/

**Comment by Cryptkeeper** [comment]
Moving discussion into https://github.com/Cryptkeeper/Minetrack/issues/83
