### ISSUE TITLE
Request of adding a server at minetrack.me

### ISSUE THREAD

**Issue by Snake1999** [Cryptkeeper/Minetrack#98]
Dear @Cryptkeeper, 

Hello! 
I am Lin Mulan, framework developer of EaseCation Network, and on behalf of our Team, I am writing to convey our request of adding our server to minetrack.me.
EaseCation is a Minecraft bedrock (Pocket Edition) server hosted in China, which has a maximum online user count of ~15,000. We focus on Minecraft mini-games. We've signed a cooperative agreement with NetEase, the exclusive operator of Minecraft in China. All minecraft Chinese-version bedrock clients have a join button to our EaseCation (like the international version has join buttons for Hypixel, Lifeboat, InPvP etc).
Adding our server into minetrack.me will increase your website visits, thus will bring both minetrack and your Hypixel more popularity. We will be very glad if our EaseCation will be tracked and recorded in china.minetrack.me and bedrock.minetrack.me.
Our server address is enclosed. Looking forward to your reply.
Best wishes!

Yours,
Lin Mulan 

Address:
```
Name:

EaseCation  

Address:

play.easecation.net

Port:

19132

Type:

Bedrock  server

Notes:
1.  Both  Query  and  RakNet  ping-pong  are  enabled  for  tracking.
2.  There  won't  be  further  changes  on  the  address  and  port.

Lin  Mulan
```

**Comment by DaMatrix** [comment]
> *NycuRO - Today at 11:21 AM*
https://status.potestas.xyz/
(at)SupremeMortal Can you add and EaseCation?

> *SupremeMortal - Today at 11:47 AM*
No because the player count is fake

:thinking:

**Comment by Snake1999** [comment]
@DaMatrix It's not fake. If you are logging in with minecraft pe international version, you are transported to international server (a host in the US, with ~500 player online), but if you log in with Chinese version of minecraft PE, you will be in the Chinese server (in Hangzhou, Zhejiang, with ~30 machines and ~15000 players). This is limited by the aggrement with NetEase.

See http://intl.easecation.net:8081/ for more details.

**Comment by Snake1999** [comment]
@SupremeMortal

**Comment by ycwei982** [comment]
you should teach the author how to use NetEase Minecraft PE

**Comment by SupremeMortal** [comment]
Yes. Someone told me about the website the other day. I was unaware of a separate client.

**Comment by Snake1999** [comment]
@SupremeMortal I'm sending you a peak address, which allow you to join the Chinese servers without downloading a separate client, to your email hello@cryptkpr.me with my mailbox 237356812@qq.com . Please check your email box.

**Comment by Cryptkeeper** [comment]
Sorry for the delay. I'm closing all PRs looking to add servers to the "official" (https://minetrack.me) pages. 

I'm barely maintaining the site as is, and I'm not interested in add/removing/tweaking servers (and the arguments that come with) since I'm not involved in the Minecraft ecosystem anymore. Short of any of the currently tracked servers closing down, I don't expect any further changes to the server list.

I see you've deployed your own Minetrack and add your desired servers there. That's great and what I'm recommending most people do. Minetrack has lived a long, happy life but I think it's time for better tools :)
